# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ea8d909a69ea8c59c6997446c287172"
name = "pixelnova"
handle = "pixelnova"
application_url = "https://pixelnova-1.onrender.com/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_pixels,read_products,write_pixels,write_products,read_discounts,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://pixelnova-1.onrender.com/auth/callback",
  "https://pixelnova-1.onrender.com/auth/shopify/callback",
  "https://pixelnova-1.onrender.com/auth/callback"
]

[pos]
embedded = false
